Abbreviate ". ";
Abbreviate ", ";
Abbreviate " the ";
Abbreviate "It's a";
Abbreviate "You";
Abbreviate "The";
Abbreviate "ing";
Abbreviate "Northrup";
Abbreviate "you";
Abbreviate " and ";
Abbreviate "the";
Abbreviate "currently";
Abbreviate "button";
Abbreviate "This is";
Abbreviate "MRI scanner";
Abbreviate "It's";
Abbreviate "Nurse Retch";
Abbreviate "'re";
Abbreviate "ter";
Abbreviate "a l";
Abbreviate "She";
Abbreviate "'t need";
Abbreviate "all";
Abbreviate "He's";
Abbreviate "and";
Abbreviate " th";
Abbreviate " be";
Abbreviate " st";
Abbreviate " to";
Abbreviate " with";
Abbreviate " in";
Abbreviate " of";
Abbreviate " elevator";
Abbreviate " down";
Abbreviate " from";
Abbreviate " sh";
Abbreviate " have";
Abbreviate " here";
Abbreviate " si";
Abbreviate " a moment";
Abbreviate " see";
Abbreviate " door";
Abbreviate " fo";
Abbreviate " le";
Abbreviate " ne";
Abbreviate " large";
Abbreviate " room";
Abbreviate " some";
Abbreviate "s are";
Abbreviate " metal";
Abbreviate " pl";
Abbreviate "Sid Jorry";
Abbreviate " hospital";
Abbreviate " hi";
Abbreviate " fl";
Abbreviate " fi";
Abbreviate "I don't";
Abbreviate " lo";
Abbreviate " on";
Abbreviate " already";
Abbreviate " cl";
Abbreviate " we";
Abbreviate " bl";
Abbreviate " he";
